nameOverride: ""
fullnameOverride: ""
operatorNamespace: ""
config:
  platform-type: OpenDataHub
  platform-version: unknown
image:
  repository: quay.io/opendatahub/odh-ai-gateway-operator
  tag: odh-stable
  fullRef: ""
leaderElect: true
replicas: 1
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 10m
    memory: 128Mi
imagePullSecret: ""
serviceAccount:
  name: ""
  annotations: {}
